import re
from dataclasses import dataclass, field
from typing import List

TRANSPARENCY_NOTE = (
    "⚠️ AI-Generated Recommendation\n"
    "This output was generated by CertifyIQ's AI reasoning pipeline and grounded in "
    "organisational knowledge sources via Azure AI Foundry IQ. It should be reviewed "
    "by a qualified Learning & Development professional before implementation. "
    "CertifyIQ does not make final decisions — it supports human decision-makers."
)

_EMAIL_RE = re.compile(r"\S+@\S+\.\S+")
_PHONE_RE = re.compile(r"\d{10,}")
_SSN_RE = re.compile(r"\d{3}-\d{2}-\d{4}")
_SQL_RE = re.compile(r"\b(SELECT|DROP|INSERT|UPDATE|DELETE|EXEC|UNION)\b", re.IGNORECASE)
_SCRIPT_RE = re.compile(r"<script[^>]*>", re.IGNORECASE)
_CRED_RE = re.compile(r"(password=|api_key=|secret=|token=)", re.IGNORECASE)
_STAT_RE = re.compile(r"\d+%")
_FUTURE_DATE_RE = re.compile(r"\b(202[89]|20[3-9]\d)\b")
_GENDER_RE = re.compile(r"\b(he|she|him|her|his|hers)\b", re.IGNORECASE)
_EXCLUSION_RE = re.compile(r"\b(only|just|merely|simply)\s+\w+\s+(can|should|must)\b", re.IGNORECASE)


class ResponsibleAIGuardrails:
    def validate_input(self, text: str) -> dict:
        rules_triggered = []

        # Rule 1: No email
        if _EMAIL_RE.search(text):
            rules_triggered.append(1)
        # Rule 2: No phone
        if _PHONE_RE.search(text):
            rules_triggered.append(2)
        # Rule 3: No SSN
        if _SSN_RE.search(text):
            rules_triggered.append(3)
        # Rule 4: Length check
        if len(text) > 2000:
            rules_triggered.append(4)
        # Rule 5: Not empty
        if not text or not text.strip():
            rules_triggered.append(5)
        # Rule 6: No SQL injection
        if _SQL_RE.search(text):
            rules_triggered.append(6)
        # Rule 7: No script injection
        if _SCRIPT_RE.search(text):
            rules_triggered.append(7)
        # Rule 8: No credentials
        if _CRED_RE.search(text):
            rules_triggered.append(8)
        # Rule 9: Real company PII check (simplified)
        sensitive_orgs = ["ssn", "national insurance", "passport"]
        if any(s in text.lower() for s in sensitive_orgs):
            rules_triggered.append(9)
        # Rule 10: Encoding validation
        try:
            text.encode("utf-8")
        except Exception:
            rules_triggered.append(10)

        safe = len(rules_triggered) == 0
        return {
            "safe": safe,
            "reason": f"Rules triggered: {rules_triggered}" if rules_triggered else "Input passed all checks",
            "rules_triggered": rules_triggered,
            "cleaned_text": text,
        }

    def validate_output(self, text: str) -> dict:
        rules_triggered = []

        # Rule 11: Citation present
        if "[Source:" not in text:
            rules_triggered.append(11)
        # Rule 12: No "I don't know"
        if "I don't know" in text:
            rules_triggered.append(12)
        # Rule 13: No "I cannot"
        if "I cannot" in text:
            rules_triggered.append(13)
        # Rule 14: Length check
        if len(text) < 50 or len(text) > 3000:
            rules_triggered.append(14)
        # Rule 15: Stats without citation
        stats = _STAT_RE.findall(text)
        if stats and "[Source:" not in text:
            rules_triggered.append(15)
        # Rule 16: Future date hallucination
        if _FUTURE_DATE_RE.search(text):
            rules_triggered.append(16)
        # Rule 17: Transparency note
        if "AI-Generated" not in text and "CertifyIQ" not in text:
            rules_triggered.append(17)
        # Rule 18: No PII in output
        if _EMAIL_RE.search(text) or _SSN_RE.search(text):
            rules_triggered.append(18)
        # Rule 19: Grounding verified
        grounding_verified = "[Source:" in text
        if not grounding_verified:
            rules_triggered.append(19)
        # Rule 20: Actionable check
        action_verbs = ["schedule", "focus", "complete", "review", "block", "study", "practice", "contact", "recommend"]
        if not any(v in text.lower() for v in action_verbs):
            rules_triggered.append(20)

        safe = len([r for r in rules_triggered if r not in [11, 17, 19, 20]]) == 0  # some rules are warnings
        overall = "PASS" if not rules_triggered else ("WARN" if len(rules_triggered) <= 2 else "FAIL")
        return {
            "safe": safe,
            "reason": f"Rules triggered: {rules_triggered}" if rules_triggered else "Output passed all checks",
            "rules_triggered": rules_triggered,
            "transparency_note": TRANSPARENCY_NOTE,
            "grounding_verified": grounding_verified,
            "overall": overall,
        }

    def check_bias(self, recommendations: list) -> dict:
        rules_triggered = []
        flags = []

        for rec in recommendations:
            text = str(rec)
            # Rule 21: No role-based capability assumptions
            if re.search(r"\b(only \w+ can|just \w+ should)\b", text, re.IGNORECASE):
                rules_triggered.append(21)
                flags.append(f"Rule 21: role assumption in '{text[:60]}'")
            # Rule 22: No gender-coded language
            if _GENDER_RE.search(text):
                rules_triggered.append(22)
                flags.append(f"Rule 22: gender language in '{text[:60]}'")
            # Rule 23: No unrealistic time expectations
            if re.search(r"\b([5-9]\d+|[4-9]\d)\s*hours?\s*per\s*day\b", text, re.IGNORECASE):
                rules_triggered.append(23)
                flags.append(f"Rule 23: unrealistic time in '{text[:60]}'")
            # Rule 24: No cultural scheduling assumptions
            if re.search(r"\b(saturday|sunday)\s+is\s+(mandatory|required)\b", text, re.IGNORECASE):
                rules_triggered.append(24)
                flags.append(f"Rule 24: cultural assumption in '{text[:60]}'")
            # Rule 25: Inclusive language
            if _EXCLUSION_RE.search(text):
                rules_triggered.append(25)
                flags.append(f"Rule 25: exclusionary language in '{text[:60]}'")

        return {
            "bias_detected": len(rules_triggered) > 0,
            "rules_triggered": list(set(rules_triggered)),
            "flags": flags,
        }

    def validate_all(self, input_text: str, output_text: str, recs: list) -> dict:
        input_result = self.validate_input(input_text)
        output_result = self.validate_output(output_text)
        bias_result = self.check_bias(recs)

        all_rules = (
            input_result.get("rules_triggered", []) +
            output_result.get("rules_triggered", []) +
            bias_result.get("rules_triggered", [])
        )

        input_passed = input_result["safe"]
        output_passed = output_result["safe"]
        bias_passed = not bias_result["bias_detected"]

        if not input_passed:
            overall = "FAIL"
        elif not output_passed or not bias_passed:
            overall = "WARN"
        else:
            overall = "PASS"

        rules_passed = 25 - len(set(all_rules))

        return {
            "input_passed": input_passed,
            "output_passed": output_passed,
            "bias_passed": bias_passed,
            "rules_triggered": list(set(all_rules)),
            "rules_passed_count": rules_passed,
            "rules_total": 25,
            "overall": overall,
            "transparency_note": TRANSPARENCY_NOTE,
        }


guardrails = ResponsibleAIGuardrails()